### ISSUE TITLE
im getting error when manual linking in react natve

### ISSUE THREAD

**Issue by cibinstark123** [mkharibalaji/react-native-adyen-payment#12]
///mainapplication.java
error: package com.reactlibrary does not exist
import com.reactlibrary.AdyenPaymentPackage;
&&&&&
cannot find symbol
          packages.add(new AdyenPaymentPackage(this).getPackages());
                           ^
  symbol: class AdyenPaymentPackage
![Screenshot (99)](https://user-images.githubusercontent.com/47915530/80078103-0f6d3980-856c-11ea-9dd5-8ce1e89862a4.png)

**Comment by crherman7** [comment]
@cibinstark123 how did you fix this?
