### ISSUE TITLE
CocoaPods could not find compatible versions for pod "react-native-adyen-payment"

### ISSUE THREAD

**Issue by duynd1** [mkharibalaji/react-native-adyen-payment#2]
Hi!
After running :
`pod install`
 I get an error like this.
[!] CocoaPods could not find compatible versions for pod "react-native-adyen-payment":
  In Podfile:
    react-native-adyen-payment (from `../node_modules/react-native-adyen-payment`)

Specs satisfying the `react-native-adyen-payment (from `../node_modules/react-native-adyen-payment`)` dependency were found, but they required a higher minimum deployment target.

Please help me!! I try to follow this steps but not working
"react-native": "0.61.4" , platform :ios, '9.0'

**Comment by mkharibalaji** [comment]
Hi @duynd1 ,
             Minimum s.ios.deployment_target = '10.0' for Adyen ,so i bumped it to 11 in react-native-adyen-payment podspec to 11.I haven't tested it on 10,but it should work.Currently the minimum version set in react-native-adyen-payment.podspec is 11.

            Please raise a PR if it works in platform : ios '10' by changing the file react-native-adyen-payment.podspec

**Comment by duynd1** [comment]
Hi @mkharibalaji ,
It's working , when I set version is 11. Thank you for your help
