### ISSUE TITLE
The data couldn't be read because it is missing!

### ISSUE THREAD

**Issue by duynd1** [mkharibalaji/react-native-adyen-payment#3]
Hi,
I'm integrating the library, but I stuck on the step to Show Adyen DropIn.
I think the shopper's information in the paymentDetails object is wrong, but I don't know how can I get that information in the Adyen test account.
Can you advise me ?
<img width="225" alt="Screen Shot 2020-01-06 at 2 31 31 PM" src="https://user-images.githubusercontent.com/42399744/71802925-e34bac80-3091-11ea-802b-0b1810f8558e.png">

Thanks.

**Comment by mkharibalaji** [comment]
Hi @duynd1 ,
         Can you get me some more details on the payment method you are trying and any sample data that you are trying would be helpful.
         I cannot interpret the above message.

Thanks

**Comment by voslartomas** [comment]
@mkharibalaji Hello, why do you need to have server with /payments (etc...) POST endpoints? What if one have for instance graphql server...

This is not really flexible solution. It should be possible to call server (however developer wants) and result of this call return to this library, right?

**Comment by dvdhoek** [comment]
For anyone else who runs into this issue. We had the same issue because we didn't follow the example correctly. You have to either setup your own API server or use the demo server Adyen provides. Keys can be found inside the corresponding user account.

**Comment by zvone00** [comment]
For me, the problem was the wrong country code
