### ISSUE TITLE
`onError()` listener and `Promise.reject()` not running on Android

### ISSUE THREAD

**Issue by murrple-1** [mkharibalaji/react-native-adyen-payment#8]
After applying the pull request #7 manually to bypass the crash, I am seeing unexpected behaviour on Android.

When calling `startPayment()` with `onError` set, cancelling the payment by clicking off the overlay does not call the `onError` listener. This is different from how it's behaving on iOS, where pressing `Cancel` calls the listener with `code = "ERROR_CANCELLED"` and `error = "Transaction Cancelled"`.

Similarly, calling `startPaymentPromise()` in this way:
```javascript
(async () => {
    try {
        const response = await AdyenPayment.startPaymentPromise(AdyenPayment.SCHEME, componentData, paymentDetails);
        console.log('Success', response);
    } catch (e) {
        console.log('Error', e);
    }
})();
```

does not cause the catch block to be run. This is unexpected (though this is consistent with iOS, second issue incoming).

**Comment by mkharibalaji** [comment]
Is this happening for only for "Cancelling" Action ?

**Comment by murrple-1** [comment]
On Android, there is not a "Cancel" button like on iOS. You either drag the pop-over off the screen, or you click off it to make it cancel. I have supplied a GIF to show behaviour.

<img src="https://media.giphy.com/media/J5vJoeyhOc7YJF1Bv4/giphy.gif">

**Comment by mkharibalaji** [comment]
I just sticked with the dropIn modal of adyen and had plans for customizing the ui where i thought of adding cancel button.

**Comment by mkharibalaji** [comment]
The BottomSheet State needs to tracked w.r.to PaymentMethods to track the cancelling behaviour.working on it.

**Comment by mkharibalaji** [comment]
Issue Fixed. Please test and let me know.

**Comment by murrple-1** [comment]
I haven't fully tested this due to some issues around the project in general, but initially this looks good. I will post back with an update further, hopefully soon.
